"""initial_schemas

Revision ID: c554cac77c8c
Revises: 
Create Date: 2026-07-28 13:36:08.831280+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Always imported: autogenerate emits `geoalchemy2.types.Geography(...)`
# for PostGIS columns but does not add the import itself.
import geoalchemy2  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c554cac77c8c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_otp_codes_phone'), 'otp_codes', ['phone'], unique=False, schema='auth')
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    schema='auth'
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='payment'
    )
    op.create_index('idx_payment_ride', 'transactions', ['ride_id'], unique=False, schema='payment')
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('vehicle_category', sa.String(length=20), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('surge_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ride'
    )
    op.create_table('driver_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='ride'
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['ride.driver_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number'),
    schema='ride'
    )
    op.create_geospatial_table('rides',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('passenger_user_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pickup_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('dropoff_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('dropoff_address', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('estimated_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('payment_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['ride.driver_profiles.id'], ),
    sa.ForeignKeyConstraint(['passenger_user_id'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['ride.vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ride'
    )
    op.create_geospatial_index('idx_rides_dropoff_location', 'rides', ['dropoff_location'], unique=False, schema='ride', postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_rides_pickup_location', 'rides', ['pickup_location'], unique=False, schema='ride', postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_ride_rides_passenger_user_id'), 'rides', ['passenger_user_id'], unique=False, schema='ride')
    op.create_index(op.f('ix_ride_rides_status'), 'rides', ['status'], unique=False, schema='ride')
    op.create_table('ride_ratings',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('rater_role', sa.String(length=10), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ride_ratings_rating_check'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id', 'rater_role', name='ride_ratings_ride_rater_unique'),
    schema='ride'
    )
    op.create_geospatial_table('ride_route_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ride'
    )
    op.create_geospatial_index('idx_ride_route_points_location', 'ride_route_points', ['location'], unique=False, schema='ride', postgresql_using='gist', postgresql_ops={})
    op.create_table('ride_status_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ride'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ride_status_history', schema='ride')
    op.drop_geospatial_index('idx_ride_route_points_location', table_name='ride_route_points', schema='ride', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('ride_route_points', schema='ride')
    op.drop_table('ride_ratings', schema='ride')
    op.drop_index(op.f('ix_ride_rides_status'), table_name='rides', schema='ride')
    op.drop_index(op.f('ix_ride_rides_passenger_user_id'), table_name='rides', schema='ride')
    op.drop_geospatial_index('idx_rides_pickup_location', table_name='rides', schema='ride', postgresql_using='gist', column_name='pickup_location')
    op.drop_geospatial_index('idx_rides_dropoff_location', table_name='rides', schema='ride', postgresql_using='gist', column_name='dropoff_location')
    op.drop_geospatial_table('rides', schema='ride')
    op.drop_table('vehicles', schema='ride')
    op.drop_table('driver_profiles', schema='ride')
    op.drop_table('pricing_rules', schema='ride')
    op.drop_index('idx_payment_ride', table_name='transactions', schema='payment')
    op.drop_table('transactions', schema='payment')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_otp_codes_phone'), table_name='otp_codes', schema='auth')
    op.drop_table('otp_codes', schema='auth')
    # ### end Alembic commands ###
